"""empty message

Revision ID: 74fdcaae1e33
Revises: ad66092d6f03
Create Date: 2019-05-16 10:43:31.303800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fdcaae1e33'
down_revision = 'ad66092d6f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baobiaotoset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baobiaotoset_file'), 'baobiaotoset', ['file'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_name'), 'reports', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('dept', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reports_name'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_baobiaotoset_file'), table_name='baobiaotoset')
    op.drop_table('baobiaotoset')
    # ### end Alembic commands ###
