"""empty message

Revision ID: f4e73f523906
Revises: 
Create Date: 2019-07-04 16:45:55.650404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e73f523906'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_name'), 'reports', ['name'], unique=True)
    op.create_table('baobiaotoset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=100), nullable=True),
    sa.Column('freq', sa.String(length=10), nullable=True),
    sa.Column('auditor', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['auditor'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baobiaotoset_file'), 'baobiaotoset', ['file'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baobiaotoset_file'), table_name='baobiaotoset')
    op.drop_table('baobiaotoset')
    op.drop_index(op.f('ix_reports_name'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
